# Tcl package index file, version 1.0
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Dpwe_CgiUtils 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_CgiUtils 0.1 {{cgi-utils.tcl source {CheckGetEnvironment CheckPostEnvironment ErrorExit GetGetVars GetMultipartFileVar GetMultipartPart GetMultipartSimpleVar GetPostMultipart GetPostVars GetSimpleGetVars SplitAndAssign UplevelVars hex2chr plus2spc}}}]
package ifneeded Dpwe_Utilfns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Utilfns 0.1 {{utilfns.tcl source {Assert CanvTextDims Error GetCLVars GetICSIargs DrspeechGetargs DrspeechUsage Incr LoadProfileFile Open SaveProfileFile SpeechArch SubsFile UniqFreq Warn WinHeight WinWidth _compareCarNum car cdr cons getMeanSd getenv lassign last lintersect lmap lunion lwithout lwithoutl lwithoutl_simple max min nth processProcArgs quit regmod resetArray reverse stringreplace sum uniqueCommand uptochr}}}]
package ifneeded Dpwe_Labelfilefns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Labelfilefns 0.1 {{labelfilefns.tcl source {CanvAddLabels DursToLabels LabelsClick LabelsMove LabelsRelease LabelsToDurs ReadLabelFile ReadLabelFileCTM ReadLabelFileNW ReadLabelFileNW2 ReadLabelFileTI ReadLabelFileXL WriteLabelFile WriteLabelFileNW WriteLabelFileTI WriteLabelFileXL WavSamplesSafe WavSamplesQuick FullFileName ReadLabelFilePF}}}]
package ifneeded Dpwe_Phonesetfns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Phonesetfns 0.1 {{phonesetfns.tcl source {ReadPhsetFile ReadPhoneset PhoneName PhoneIndexOld PhoneIndex Setup61to56 Setup61to54}}}]
package ifneeded Dpwe_Datefns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Datefns 0.1 {{datefns.tcl source {now Warn val parseTime DefaultTimeZone tzNameToNum tzNumToName parseDate shortDate danDate timeFmtSecs timeFmt CanonicalDays InvCanonicalDays DayOfWeek Capitalize medTime medDate padLen rpadLen Date2Secs Secs2Date}}}]
package ifneeded Dpwe_Webfns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Webfns 0.1 {{webfns.tcl source {GetURL}}}]
package ifneeded Dpwe_Dictfns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Dictfns 0.1 {{dictfilefns.tcl source {GetDictDef SetDictDef ReadDictNW WriteDictNW}}}]
package ifneeded Dpwe_Syllifns 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Syllifns 0.1 {{syllifyfns.tcl source {Syllify_Init OpenTsylb syllify SyllabifyLabels MakeSylLabs syllify_lexicon}}}]
package ifneeded Dpwe_Rdprocmgr 0.1 [list tclPkgSetup $dir/dpwe_tcl Dpwe_Rdprocmgr 0.1 {{rdprocmgr.tcl source {rdprocAdd rdprocRemove rdprocEnable rdprocDisable rdprocClosePipe}}}]
